[package]
name = "msp432_razcal"
version = "0.1.0"
authors = ["Raz <raz-@outlook.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
paste = "1.0"
seq-macro = "0.2"

[build-dependencies]
serde = { version = "1.0.104", features = ["derive"] }
toml = "0.5.6"